name: Build Microservice and Generate Kubernetes manifests

on:
  push:
    branches:
      - 'main'
    paths:
      - "microservice/**"
      - "!microservice/kustomize/**"

permissions: read-all

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    {% raw %}
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
        name: Checkout
      - name: Log in to the Container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    {% endraw %}
      - name: Build and push Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          context: microservice
          push: true
          file: microservice/Dockerfile
          tags: ghcr.io/${{values.destination.owner}}/${{values.component_id}}:${{ '${{ github.sha }}' }},ghcr.io/${{values.destination.owner}}/${{values.component_id}}:latest

  generate:
    name: Generate Kubernetes manifests
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
        name: Checkout
      - uses: imranismail/setup-kustomize@6691bdeb1b0a3286fb7f70fd1423c10e81e5375f # v2.0.0
        name: Setup Kustomize
      - run: |
          kustomize edit set image goapp=ghcr.io/${{values.destination.owner}}/${{values.component_id}}:${{ '${{ github.sha }}' }}
          cat kustomization.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"
        working-directory: microservice/kustomize
        name: Update image tag
      - name: push
        uses: ad-m/github-push-action@master
