apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{values.name}}
  description: The Kubernetes cluster for the ${{values.stack}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    pulumi.com/owner: ${{values.organization }}
  links:
    - title: Cloud Console
      {%- if values.cloud == "scw" %}
      url: https://console.scaleway.com/kubernetes/clusters/${{values.id}}
      {%- elif values.cloud == "civo" %}
      url: https://dashboard.civo.com/kubernetes/${{values.id}}
      {%- endif %}
    - title: Pulumi Console
      url: https://app.pulumi.com/${{values.organization}}/${{values.name}}/${{values.stack}}
spec:
  type: kubernetes
  owner: ${{values.owner | dump}}
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
