apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{values.namme}}
  description: The Kubernetes cluster for the ${{values.stack}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    pulumi.com/owner: ${{values.organization }}
  links:
    - title: Cloud Console
      {%- if values.cloud == "scw" %}
      url: https://console.scaleway.com/kubernetes/clusters/${{values.id}}
      {%- elif values.cloud == "civo" %}
      url: https://dashboard.civo.com/kubernetes/${{values.id}}
      {%- endif %}
spec:
  type: kubernetes
  owner: ${{values.owner | dump}}
  lifecycle: experimental
