apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}-service
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    pulumi.com/owner: ${{values.organization }}
spec:
  type: service
  lifecycle: development
  owner: ${{values.owner | dump}}
  dependsOn:
    - ${{values.dependsOn}}
