apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ms-kubernetes-destroy-template
  title: Microservice Kubernetes Destroy Template
  description: |
    A template for destroying a Microservice on Civo Kubernetes.
    This template will destroy following components:
    - Kubernetes cluster on Civo per stage
    - Tekton pipeline to build and deploy the microservice
    - ArgoCD to deploy the microservice
  tags:
    - pulumi
    - microservice
    - kubernetes
    - tekton
    - argocd
spec:
  owner: user:dirien
  type: operations
  parameters:
    - title: Provide project informations
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component.
          ui:field: EntityNamePicker
        stack:
          title: Select stacks
          type: array
          items:
            type: string
            enum:
              - dev
              - staging
              - prod
            enumNames:
              - Development
              - Staging
              - Production
          uniqueItems: true
          description: Stack to destroy
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: pulumi-destroy
      name: Run Pulumi destroy locally
      action: pulumi:run
      input:
        destroy: true
        deployment: false
        name: ${{ parameters.component_id }}
        organization: ediri
        config:
          "civo:region": "lon1"
          "civo:token": "${{ parameters.token}}"
        outputs:
          - kubeconfig
        stacks: ${{ parameters.stack }}
        args:
          - ${{ parameters.args }}
  output:
    links:
      - title: Open the Pulumi Console
        url: "https://app.pulumi.com/ediri/${{ parameters.component_id }}"
