apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: microservice-kubernetes-template
  title: Microservice on Kubernetes
  description: |
    A template to create all parts to run a microservice on Kubernetes
  tags:
    - pulumi
    - microservice
    - scaleway
spec:
  owner: user:dirien
  type: infrastructure
  parameters:
    - title: Provide project informations
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component.
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Tell us more about this component.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User
        template:
          title: Template
          type: string
          description: Template to use
          enum:
            - kubernetes-aws-go
            - kubernetes-azure-go
            - kubernetes-gcp-go
            - microservice
        stack:
          title: Stack
          type: string
          description: Stack to deploy to
        command:
          title: Pulumi Command
          type: string
          description: Command to run Pulumi
        args:
          title: Pulumi Arguments
          type: string
          description: Arguments to run Pulumi
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    - id: pulumi-new
      name: Run Pulumi new
      action: run:pulumi
      input:
        command: new
        args:
          - ${{ parameters.template }}
          - "-n ${{ parameters.component_id }}"
          - "-d \"${{ parameters.description }}\""
          - "-s ${{ parameters.stack }}"
          - "-y"
          - ${{ parameters.args }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: [ "github.com" ]
        repoVisibility: public
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps['publish'].output.repoContentsUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
